version: "3"
services:
  app:
    image: "guidebook:tag"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80
    volumes:
      - ~/.cloudvolume:/home/nginx/.cloudvolume
    env_file:
      - ./.env.v1dd
  worker:
    image: "guidebook:tag"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.cloudvolume:/root/.cloudvolume
    env_file:
      - ./.env.v1dd
    command: python guidebook/worker.py
  redis:
    image: redis:latest
    ports:
      - 6379:6379
