version: "4"
services:
  app:
    image: "guidebook:tag"
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80
    volumes:
      - ~/.cloudvolume:/home/nginx/.cloudvolume
    env_file:
      - ./.env.minnie
  worker:
    image: "guidebook:tag"
    platform: linux/amd64 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.cloudvolume:/root/.cloudvolume
    env_file:
      - ./.env.minnie
    command: python guidebook/worker.py
  redis:
    image: redis:latest
    ports:
      - 6379:6379
